name = "Betaclu"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94afc0175a8ae0f0ea65d10d4c75c98320af7b85ff7af1e23d0828cf2cc942f2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
