name = "Betaclu"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46413033cd1121a187d0525ab0f7940d89d9e15f04cf977227dbca8cb271f278"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
