name = "Betaclu"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d70c3b8c5e6a134880405cbc357cfdc4706c924519cca9eb71b344f57b935f8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
