name = "Betaclu"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e633b9da8c7478b0f1d5dc741341b7135d32caa519ebe594c048d6405bc9c6b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
