name = "Betaclu"
author = "oiipo"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aed1e1cc3ab6217583bd6b8d836e1bdd165a10db2fccbe3767cfb4ceb1fc0c2c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
