limitObtainableEnchantmentLevel = false
obtainableEnchantmentLevels = ["minecraft:sharpness/4"]
limitBookTradeLevel = false
# Default: 5
# Range: > 1
bookTradeLevelLimit = 5
modifyEnchantedBookTradeUses = false
# Default: 12
# Range: > 1
maxEnchantedBookTradeUses = 12
modifyEnchantedItemTradeUses = false
# Default: 3
# Range: > 1
maxEnchantedItemTradeUses = 3
enchantedBookTradeRestockEnabled = true
enchantedItemTradeRestockEnabled = true
enchantingTableEnabled = true
modifyMaxTablePower = false
# Default: 15
# Range: > 1
maxTablePower = 15
modifyLapisCost = false
lapisCostFormula = "id+1"
modifyXpCost = false
xpCostFormula = "id+1"
modifyEnchantWithLevelsMaxPower = false
# Default: 50
# Range: > 1
enchantWithLevelsMaxPower = 50
