#These JEI plugins will be loaded on the main thread
blacklist_async_jei_plugins = ["jepb:jei_plugin"]
mixin.perf.dynamic_resources=true
mixin.perf.faster_item_rendering=true
mixin.perf.deduplicate_location=true